version: "3.7"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    ports:
      - 8080
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
  
  db:
    container_name: mysqld
    image: mysql:5.7.21
    volumes:
      - "./data:/var/lib/mysql"
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root