version: "3"
services:
  web:
    container_name: flask
    build: ./flask
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/usr/src/app/

  db:
    container_name: mysqld
    image: mysql:5.7.21
    volumes:
      - "./data:/var/lib/mysql"
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
